/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { CustomerEntity$inboundSchema, CustomerEntity$outboundSchema, } from "./customerentity.js";
import { PaginationEntity$inboundSchema, PaginationEntity$outboundSchema, } from "./paginationentity.js";
/** @internal */
export const CustomerListEntity$inboundSchema = z.object({
    items: z.array(CustomerEntity$inboundSchema),
    pagination: PaginationEntity$inboundSchema,
});
/** @internal */
export const CustomerListEntity$outboundSchema = z.object({
    items: z.array(CustomerEntity$outboundSchema),
    pagination: PaginationEntity$outboundSchema,
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var CustomerListEntity$;
(function (CustomerListEntity$) {
    /** @deprecated use `CustomerListEntity$inboundSchema` instead. */
    CustomerListEntity$.inboundSchema = CustomerListEntity$inboundSchema;
    /** @deprecated use `CustomerListEntity$outboundSchema` instead. */
    CustomerListEntity$.outboundSchema = CustomerListEntity$outboundSchema;
})(CustomerListEntity$ || (CustomerListEntity$ = {}));
export function customerListEntityToJSON(customerListEntity) {
    return JSON.stringify(CustomerListEntity$outboundSchema.parse(customerListEntity));
}
export function customerListEntityFromJSON(jsonString) {
    return safeParse(jsonString, (x) => CustomerListEntity$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'CustomerListEntity' from JSON`);
}
//# sourceMappingURL=customerlistentity.js.map