/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import { listCustomers } from "../../funcs/listCustomers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult } from "../tools.js";
const args = {
    request: operations.ListCustomersRequest$inboundSchema,
};
export const tool$listCustomers = {
    name: "list-customers",
    description: `List all customers`,
    args,
    tool: async (client, args, ctx) => {
        const [result, apiCall] = await listCustomers(client, args.request, { fetchOptions: { signal: ctx.signal } }).$inspect();
        if (!result.ok) {
            return {
                content: [{ type: "text", text: result.error.message }],
                isError: true,
            };
        }
        const value = result.value;
        return formatResult(value, apiCall);
    },
};
//# sourceMappingURL=listCustomers.js.map