/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const GetTransactionByIdRequest$inboundSchema = z.object({
    transaction_id: z.string(),
    "x-api-key": z.string(),
}).transform((v) => {
    return remap$(v, {
        "transaction_id": "transactionId",
        "x-api-key": "xApiKey",
    });
});
/** @internal */
export const GetTransactionByIdRequest$outboundSchema = z.object({
    transactionId: z.string(),
    xApiKey: z.string(),
}).transform((v) => {
    return remap$(v, {
        transactionId: "transaction_id",
        xApiKey: "x-api-key",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var GetTransactionByIdRequest$;
(function (GetTransactionByIdRequest$) {
    /** @deprecated use `GetTransactionByIdRequest$inboundSchema` instead. */
    GetTransactionByIdRequest$.inboundSchema = GetTransactionByIdRequest$inboundSchema;
    /** @deprecated use `GetTransactionByIdRequest$outboundSchema` instead. */
    GetTransactionByIdRequest$.outboundSchema = GetTransactionByIdRequest$outboundSchema;
})(GetTransactionByIdRequest$ || (GetTransactionByIdRequest$ = {}));
export function getTransactionByIdRequestToJSON(getTransactionByIdRequest) {
    return JSON.stringify(GetTransactionByIdRequest$outboundSchema.parse(getTransactionByIdRequest));
}
export function getTransactionByIdRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => GetTransactionByIdRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'GetTransactionByIdRequest' from JSON`);
}
//# sourceMappingURL=gettransactionbyid.js.map