import { PromptCategory, type CategoryMeta, type PromptExample } from '@/types/prompt-library';

export const CATEGORY_METADATA: CategoryMeta[] = [
  {
    id: PromptCategory.PEOPLE_PORTRAITS,
    name: 'People & Portraits',
    description: 'Professional portraits, character designs, and human-focused prompts',
    icon: 'Users',
    order: 1,
    color: 'blue',
  },
  {
    id: PromptCategory.ANIMALS_WILDLIFE,
    name: 'Animals & Wildlife',
    description: 'Wildlife photography, pet portraits, and creature designs',
    icon: 'Bird',
    order: 2,
    color: 'green',
  },
  {
    id: PromptCategory.SCENERY_ENVIRONMENT,
    name: 'Scenery & Environment',
    description: 'Landscapes, cityscapes, and environmental scenes',
    icon: 'Mountain',
    order: 3,
    color: 'purple',
  },
  {
    id: PromptCategory.OBJECTS_PRODUCTS,
    name: 'Objects & Products',
    description: 'Product photography and object-focused compositions',
    icon: 'Package',
    order: 4,
    color: 'orange',
  },
  {
    id: PromptCategory.SCIENCE_EDU_TECH,
    name: 'Science, Education & Technology',
    description: 'Scientific visualizations, educational diagrams, and tech concepts',
    icon: 'Microscope',
    order: 5,
    color: 'cyan',
  },
  {
    id: PromptCategory.FASHION_LIFESTYLE,
    name: 'Fashion, Lifestyle & Aesthetic Design',
    description: 'Fashion photography, lifestyle scenes, and aesthetic designs',
    icon: 'Sparkles',
    order: 6,
    color: 'pink',
  },
];

export const PROMPT_EXAMPLES: PromptExample[] = [
  {
    id: 'runner-001',
    category: PromptCategory.PEOPLE_PORTRAITS,
    title: 'Runner Stretching at Dawn',
    prompt: 'A runner stretching before sunrise, outdoor path, dawn lighting, determined tone, sports editorial style, side composition, crisp 4K texture.',
    cloudinaryPublicId: 'prompt-library/people-portraits/nb-runner-001',
    imageUrl: '',
    tags: ['runner', 'sports', 'fitness', 'dawn', 'editorial'],
    model: 'nano-banana',
    featured: true,
    order: 1,
    metadata: {
      style: 'sports editorial',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'girl-002',
    category: PromptCategory.PEOPLE_PORTRAITS,
    title: 'Girl with Flowers in Garden',
    prompt: 'A girl holding flowers, in outdoor garden, golden hour light, peaceful and dreamy tone, modern portrait photography, side profile framing, natural color tones.',
    cloudinaryPublicId: 'prompt-library/people-portraits/nb-girl-002',
    imageUrl: '',
    tags: ['portrait', 'flowers', 'garden', 'golden hour', 'peaceful'],
    model: 'nano-banana',
    featured: false,
    order: 2,
    metadata: {
      style: 'portrait photography',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'businessman-003',
    category: PromptCategory.PEOPLE_PORTRAITS,
    title: 'Business Presentation on Stage',
    prompt: 'A young man presenting on stage, in conference room, bright spotlight, confident tone, business presentation photography style, front angle, clear composition',
    cloudinaryPublicId: 'prompt-library/people-portraits/nb-businessman-003',
    imageUrl: '',
    tags: ['business', 'presentation', 'conference', 'professional', 'stage'],
    model: 'nano-banana',
    featured: false,
    order: 3,
    metadata: {
      style: 'business photography',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'womancoffee-004',
    category: PromptCategory.PEOPLE_PORTRAITS,
    title: 'Woman with Coffee by Window',
    prompt: 'A woman holding coffee cup by window, morning light, cozy and thoughtful tone, lifestyle realism, mid composition, warm balance.',
    cloudinaryPublicId: 'prompt-library/people-portraits/nb-womancoffee-004',
    imageUrl: '',
    tags: ['woman', 'coffee', 'window', 'lifestyle', 'cozy'],
    model: 'nano-banana',
    featured: false,
    order: 4,
    metadata: {
      style: 'lifestyle realism',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'polar-bear-001',
    category: PromptCategory.ANIMALS_WILDLIFE,
    title: 'Polar Bear in Arctic Sunset',
    prompt: 'A polar bear walking across ice floes, in Arctic sunset, cool pastel lighting, tranquil yet grand tone, cinematic nature film style, wide composition, realistic snow texture.',
    cloudinaryPublicId: 'prompt-library/animals-wildlife/nb-polar-bear-001',
    imageUrl: '',
    tags: ['polar bear', 'arctic', 'sunset', 'wildlife', 'cinematic'],
    model: 'nano-banana',
    featured: true,
    order: 1,
    metadata: {
      style: 'cinematic',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'lion-002',
    category: PromptCategory.ANIMALS_WILDLIFE,
    title: 'Lion Roaring in Savanna',
    prompt: 'A lion roaring atop a rock, in golden savanna, sunrise backlight, majestic and powerful mood, National Geographic style, telephoto composition, ultra-detailed fur 8K.',
    cloudinaryPublicId: 'prompt-library/animals-wildlife/nb-lion-002',
    imageUrl: '',
    tags: ['lion', 'savanna', 'wildlife', 'sunrise', 'majestic'],
    model: 'nano-banana',
    featured: false,
    order: 2,
    metadata: {
      style: 'National Geographic',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'flamingo-003',
    category: PromptCategory.ANIMALS_WILDLIFE,
    title: 'Flamingos at Dawn',
    prompt: 'A group of flamingos reflected in shallow water, at dawn, warm orange lighting, elegant and serene mood, minimalist photography style, mirror symmetry composition, 8K clarity.',
    cloudinaryPublicId: 'prompt-library/animals-wildlife/nb-flamingo-003',
    imageUrl: '',
    tags: ['flamingo', 'water', 'reflection', 'dawn', 'serene'],
    model: 'nano-banana',
    featured: false,
    order: 3,
    metadata: {
      style: 'minimalist',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'castle-001',
    category: PromptCategory.SCENERY_ENVIRONMENT,
    title: 'Medieval Castle in Clouds',
    prompt: 'A medieval castle atop a mountain surrounded by clouds, dawn lighting, epic and timeless tone, fantasy concept art, wide composition, HDR realism.',
    cloudinaryPublicId: 'prompt-library/scenery-environment/nb-castle-001',
    imageUrl: '',
    tags: ['castle', 'mountain', 'clouds', 'medieval', 'epic'],
    model: 'nano-banana',
    featured: true,
    order: 1,
    metadata: {
      style: 'fantasy concept art',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'desertcity-002',
    category: PromptCategory.SCENERY_ENVIRONMENT,
    title: 'Desert City at Sunset',
    prompt: 'A desert city built with sandstone towers, glowing under sunset light, warm and exotic tone, cinematic adventure style, panoramic view, high detail.',
    cloudinaryPublicId: 'prompt-library/scenery-environment/nb-desertcity-002',
    imageUrl: '',
    tags: ['desert', 'city', 'sunset', 'exotic', 'cinematic'],
    model: 'nano-banana',
    featured: false,
    order: 2,
    metadata: {
      style: 'cinematic',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'town-003',
    category: PromptCategory.SCENERY_ENVIRONMENT,
    title: 'European Town Square at Dusk',
    prompt: 'A quiet European town square at dusk, golden hour lighting, nostalgic and calm tone, travel photography style, centered framing, high fidelity texture.',
    cloudinaryPublicId: 'prompt-library/scenery-environment/nb-town-003',
    imageUrl: '',
    tags: ['town', 'europe', 'dusk', 'nostalgic', 'travel'],
    model: 'nano-banana',
    featured: false,
    order: 3,
    metadata: {
      style: 'travel photography',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'camera-001',
    category: PromptCategory.OBJECTS_PRODUCTS,
    title: 'Vintage Camera and Coffee',
    prompt: 'A vintage camera placed beside coffee cup, on wooden table, warm morning light, nostalgic and cozy tone, cinematic lifestyle shot, shallow depth of field, realistic texture.',
    cloudinaryPublicId: 'prompt-library/objects-products/nb-camera-001',
    imageUrl: '',
    tags: ['camera', 'coffee', 'vintage', 'nostalgic', 'lifestyle'],
    model: 'nano-banana',
    featured: true,
    order: 1,
    metadata: {
      style: 'lifestyle photography',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'phone-002',
    category: PromptCategory.OBJECTS_PRODUCTS,
    title: 'Futuristic Smartphone',
    prompt: 'A sleek smartphone floating in air, with neon background, modern and futuristic tone, digital advertising style, centered composition, ultra sharp lighting.',
    cloudinaryPublicId: 'prompt-library/objects-products/nb-phone-002',
    imageUrl: '',
    tags: ['smartphone', 'technology', 'futuristic', 'neon', 'advertising'],
    model: 'nano-banana',
    featured: false,
    order: 2,
    metadata: {
      style: 'advertising',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'perfume-003',
    category: PromptCategory.OBJECTS_PRODUCTS,
    title: 'Luxury Perfume Bottle',
    prompt: 'A perfume bottle surrounded by mist, in dark luxury studio lighting, mysterious and premium mood, fashion editorial photography, close-up, glossy reflections.',
    cloudinaryPublicId: 'prompt-library/objects-products/nb-perfume-003',
    imageUrl: '',
    tags: ['perfume', 'luxury', 'premium', 'mist', 'editorial'],
    model: 'nano-banana',
    featured: false,
    order: 3,
    metadata: {
      style: 'editorial',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'coffee-004',
    category: PromptCategory.OBJECTS_PRODUCTS,
    title: 'Coffee Latte Art',
    prompt: 'A cup of coffee with latte art, in minimalist cafe table setting, soft daylight, warm and inviting mood, lifestyle realism, top-down composition, realistic foam detail.',
    cloudinaryPublicId: 'prompt-library/objects-products/nb-coffee-004',
    imageUrl: '',
    tags: ['coffee', 'latte art', 'cafe', 'minimalist', 'warm'],
    model: 'nano-banana',
    featured: false,
    order: 4,
    metadata: {
      style: 'lifestyle',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'spaceship-001',
    category: PromptCategory.SCIENCE_EDU_TECH,
    title: 'Astronaut in Space Station',
    prompt: 'An astronaut floating inside space station, Earth visible outside, soft blue lighting, calm and awe-inspiring tone, cinematic composition, HDR realism.',
    cloudinaryPublicId: 'prompt-library/science-edu-tech/nb-spaceship-001',
    imageUrl: '',
    tags: ['astronaut', 'space', 'station', 'earth', 'sci-fi'],
    model: 'nano-banana',
    featured: true,
    order: 1,
    metadata: {
      style: 'cinematic',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: '3Dprinter-002',
    category: PromptCategory.SCIENCE_EDU_TECH,
    title: '3D Printer in Workshop',
    prompt: 'A 3D printer creating mechanical part, in modern workshop, cool tone, inventive and modern mood, industrial realism style, macro detail, HDR sharpness.',
    cloudinaryPublicId: 'prompt-library/science-edu-tech/nb-3Dprinter-002',
    imageUrl: '',
    tags: ['3D printer', 'technology', 'workshop', 'industrial', 'modern'],
    model: 'nano-banana',
    featured: false,
    order: 2,
    metadata: {
      style: 'industrial',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'robotics-003',
    category: PromptCategory.SCIENCE_EDU_TECH,
    title: 'Robotics Kit on Desk',
    prompt: 'A robotics kit on desk, daylight tone, innovative and playful mood, educational photography, top-down composition, balanced contrast.',
    cloudinaryPublicId: 'prompt-library/science-edu-tech/nb-robotics-003',
    imageUrl: '',
    tags: ['robotics', 'education', 'technology', 'desk', 'learning'],
    model: 'nano-banana',
    featured: false,
    order: 3,
    metadata: {
      style: 'educational photography',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'telescope-004',
    category: PromptCategory.SCIENCE_EDU_TECH,
    title: 'Telescope Aimed at Stars',
    prompt: 'A telescope aimed at starry sky, night lighting, calm and exploratory tone, astrophotography style, long exposure, detailed starscape.',
    cloudinaryPublicId: 'prompt-library/science-edu-tech/nb-telescope-004',
    imageUrl: '',
    tags: ['telescope', 'astronomy', 'stars', 'night', 'exploration'],
    model: 'nano-banana',
    featured: false,
    order: 4,
    metadata: {
      style: 'astrophotography',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'model-001',
    category: PromptCategory.FASHION_LIFESTYLE,
    title: 'Model in Desert Dunes',
    prompt: 'A model posing in flowing silk dress, in desert dunes, golden hour lighting, elegant and timeless tone, Vogue editorial style, wide shot, ultra detailed 8K.',
    cloudinaryPublicId: 'prompt-library/fashion-lifestyle/nb-model-001',
    imageUrl: '',
    tags: ['fashion', 'model', 'desert', 'editorial', 'elegant'],
    model: 'nano-banana',
    featured: true,
    order: 1,
    metadata: {
      style: 'editorial',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'coupleparis-002',
    category: PromptCategory.FASHION_LIFESTYLE,
    title: 'Couple in Paris',
    prompt: 'A couple walking in Paris street, sunset light, romantic and stylish tone, cinematic lifestyle photo, wide composition, film grain finish.',
    cloudinaryPublicId: 'prompt-library/fashion-lifestyle/nb-coupleparis-002',
    imageUrl: '',
    tags: ['couple', 'paris', 'romantic', 'lifestyle', 'cinematic'],
    model: 'nano-banana',
    featured: false,
    order: 2,
    metadata: {
      style: 'cinematic lifestyle',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'mantakephoto-003',
    category: PromptCategory.FASHION_LIFESTYLE,
    title: 'Person Taking Photo with Phone',
    prompt: 'A person taking photo with phone, sunlight reflections, candid and trendy tone, street realism, dynamic framing, crisp focus.',
    cloudinaryPublicId: 'prompt-library/fashion-lifestyle/nb-mantakephoto-003',
    imageUrl: '',
    tags: ['photography', 'street', 'phone', 'candid', 'trendy'],
    model: 'nano-banana',
    featured: false,
    order: 3,
    metadata: {
      style: 'street realism',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
  {
    id: 'holdingflowers-004',
    category: PromptCategory.FASHION_LIFESTYLE,
    title: 'Person Arranging Flowers',
    prompt: 'A person arranging flowers in vase, soft indoor lighting, calm and aesthetic tone, lifestyle realism, close-up, clean exposure.',
    cloudinaryPublicId: 'prompt-library/fashion-lifestyle/nb-holdingflowers-004',
    imageUrl: '',
    tags: ['flowers', 'lifestyle', 'aesthetic', 'calm', 'arrangement'],
    model: 'nano-banana',
    featured: false,
    order: 4,
    metadata: {
      style: 'lifestyle realism',
      aspectRatio: '1:1',
      quality: 'high',
    },
  },
];
