/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the creem SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx retrieveProduct.example.ts
 */

import { Creem } from "creem";

const creem = new Creem();

async function main() {
  const result = await creem.retrieveProduct({
    productId: "<id>",
    xApiKey: "<value>",
  });

  console.log(result);
}

main().catch(console.error);
