/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
/** @internal */
export const ListCustomersRequest$inboundSchema = z.object({
    page_number: z.number().optional(),
    page_size: z.number().optional(),
    "x-api-key": z.string(),
}).transform((v) => {
    return remap$(v, {
        "page_number": "pageNumber",
        "page_size": "pageSize",
        "x-api-key": "xApiKey",
    });
});
/** @internal */
export const ListCustomersRequest$outboundSchema = z.object({
    pageNumber: z.number().optional(),
    pageSize: z.number().optional(),
    xApiKey: z.string(),
}).transform((v) => {
    return remap$(v, {
        pageNumber: "page_number",
        pageSize: "page_size",
        xApiKey: "x-api-key",
    });
});
/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export var ListCustomersRequest$;
(function (ListCustomersRequest$) {
    /** @deprecated use `ListCustomersRequest$inboundSchema` instead. */
    ListCustomersRequest$.inboundSchema = ListCustomersRequest$inboundSchema;
    /** @deprecated use `ListCustomersRequest$outboundSchema` instead. */
    ListCustomersRequest$.outboundSchema = ListCustomersRequest$outboundSchema;
})(ListCustomersRequest$ || (ListCustomersRequest$ = {}));
export function listCustomersRequestToJSON(listCustomersRequest) {
    return JSON.stringify(ListCustomersRequest$outboundSchema.parse(listCustomersRequest));
}
export function listCustomersRequestFromJSON(jsonString) {
    return safeParse(jsonString, (x) => ListCustomersRequest$inboundSchema.parse(JSON.parse(x)), `Failed to parse 'ListCustomersRequest' from JSON`);
}
//# sourceMappingURL=listcustomers.js.map